In [1]:
# test_model.py
import numpy as np
from grabscreen import grab_screen
import cv2
import time
from directkeys import PressKey,ReleaseKey, W, A, S, D
from alexnet import alexnet
from getkeys import key_check

import random

WIDTH = 160
HEIGHT = 120
LR = 1e-3
EPOCHS = 10
MODEL_NAME = 'pygta5-car-fast-{}-{}-{}-epochs-300K-data.model'.format(LR, 'alexnetv2',EPOCHS)

t_time = 0.09

def straight():
##    if random.randrange(4) == 2:
##        ReleaseKey(W)
##    else:
    PressKey(W)
    ReleaseKey(A)
    ReleaseKey(D)

def left():
    PressKey(W)
    PressKey(A)
    #ReleaseKey(W)
    ReleaseKey(D)
    #ReleaseKey(A)
    time.sleep(t_time)
    ReleaseKey(A)

def right():
    PressKey(W)
    PressKey(D)
    ReleaseKey(A)
    #ReleaseKey(W)
    #ReleaseKey(D)
    time.sleep(t_time)
    ReleaseKey(D)
    
model = alexnet(WIDTH, HEIGHT, LR)
model.load(MODEL_NAME)

def main():
    last_time = time.time()
    for i in list(range(4))[::-1]:
        print(i+1)
        time.sleep(1)

    paused = False
    while(True):
        
        if not paused:
            # 800x600 windowed mode
            #screen =  np.array(ImageGrab.grab(bbox=(0,40,800,640)))
            screen = grab_screen(region=(0,40,800,640))
            print('loop took {} seconds'.format(time.time()-last_time))
            last_time = time.time()
            screen = cv2.cvtColor(screen, cv2.COLOR_BGR2GRAY)
            screen = cv2.resize(screen, (160,120))

            prediction = model.predict([screen.reshape(160,120,1)])[0]
            print(prediction)

            turn_thresh = .75
            fwd_thresh = 0.70

            if prediction[1] > fwd_thresh:
                straight()
            elif prediction[0] > turn_thresh:
                left()
            elif prediction[2] > turn_thresh:
                right()
            else:
                straight()

        keys = key_check()

        # p pauses game and can get annoying.
        if 'T' in keys:
            if paused:
                paused = False
                time.sleep(1)
            else:
                paused = True
                ReleaseKey(A)
                ReleaseKey(W)
                ReleaseKey(D)
                time.sleep(1)

main()      


curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
INFO:tensorflow:Restoring parameters from C:\Users\Acer\Desktop\Project_CSE_3rd Sem\Deep Learning Module\pygta5-car-fast-0.001-alexnetv2-10-epochs-300K-data.model
4
3
2
1
loop took 4.539658069610596 seconds
[0.37062496 0.6280916  0.00128345]
loop took 3.0499985218048096 seconds
[0.21447076 0.7846245  0.00090476]
loop took 0.032174110412597656 seconds
[0.21447076 0.7846245  0.00090476]
loop took 0.04323840141296387 seconds
[0.21447076 0.7846245  0.00090476]
loop took 0.02881646156311035 seconds
[0.21447076 0.7846245  0.00090476]
loop took 0.030440092086791992 seconds
[0.21447076 0.7846245  0.00090476]
loop took 0.03176474571228027 seconds
[0.21447076 0.7846245  0.00090476]
loop took 0.04260778

loop took 0.03424835205078125 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03264617919921875 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03400015830993652 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03249096870422363 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.032982826232910156 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.01666712760925293 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.04180335998535156 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.02548980712890625 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03226423263549805 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03291010856628418 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.0339353084564209 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.032929420471191406 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03351092338562012 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03315305709838867 seconds
[0.05119573 

[0.05119573 0.9467991  0.00200519]
loop took 0.03453969955444336 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.032698869705200195 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03286457061767578 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03316044807434082 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.04644489288330078 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.020491361618041992 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.033066749572753906 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03326988220214844 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.041825056076049805 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.02515101432800293 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03320670127868652 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03344893455505371 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.046250104904174805 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0

[0.05119573 0.9467991  0.00200519]
loop took 0.03460216522216797 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.046044349670410156 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.018573284149169922 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03445744514465332 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03290724754333496 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.01564788818359375 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.025738239288330078 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.033297061920166016 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.023993253707885742 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03309941291809082 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03369855880737305 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.033086299896240234 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03368997573852539 seconds
[0.05119573 0.9467991  0.00200519]
loop took 

loop took 0.03572845458984375 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.0266568660736084 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.032857418060302734 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03283214569091797 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03388667106628418 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.038314104080200195 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.02803492546081543 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03320574760437012 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03358054161071777 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.016592025756835938 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.01662611961364746 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.0330355167388916 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03292202949523926 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03278088569641113 seconds
[0.05119573 

loop took 0.03370547294616699 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03271150588989258 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03349423408508301 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03261232376098633 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.033277273178100586 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03280496597290039 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03383445739746094 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03287363052368164 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03389883041381836 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03286337852478027 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03359079360961914 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03330349922180176 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.04856586456298828 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.033666133880615234 seconds
[0.05119573

[0.05119573 0.9467991  0.00200519]
loop took 0.03370952606201172 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03341245651245117 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03323674201965332 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.032912254333496094 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.04838895797729492 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.04219555854797363 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.031025409698486328 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03217315673828125 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.02735733985900879 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.04778265953063965 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03601813316345215 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.04712271690368652 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.035877227783203125 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.0

[0.05119573 0.9467991  0.00200519]
loop took 0.0334019660949707 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.032094478607177734 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03385734558105469 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.015604019165039062 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.016855716705322266 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.016411304473876953 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.01654219627380371 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.01659083366394043 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.033037662506103516 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03416752815246582 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.03275656700134277 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.01628565788269043 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.01656937599182129 seconds
[0.05119573 0.9467991  0.00200519]
loop took 0.

[0.10231505 0.870294   0.02739105]
loop took 0.03271985054016113 seconds
[0.10231505 0.870294   0.02739105]
loop took 0.04647421836853027 seconds
[0.10231505 0.870294   0.02739105]
loop took 0.036423444747924805 seconds
[0.09253079 0.8801224  0.02734679]
loop took 0.032792091369628906 seconds
[0.09253079 0.8801224  0.02734679]
loop took 0.0331730842590332 seconds
[0.10231505 0.870294   0.02739105]
loop took 0.03361010551452637 seconds
[0.13555326 0.8325913  0.03185545]
loop took 0.03346967697143555 seconds
[0.13555326 0.8325913  0.03185545]
loop took 0.03235983848571777 seconds
[0.13555326 0.8325913  0.03185545]
loop took 0.03318476676940918 seconds
[0.13555326 0.8325913  0.03185545]
loop took 0.016589879989624023 seconds
[0.13555326 0.8325913  0.03185545]
loop took 0.03378796577453613 seconds
[0.13555326 0.8325913  0.03185545]
loop took 0.03318476676940918 seconds
[0.09765709 0.8747837  0.02755923]
loop took 0.03415846824645996 seconds
[0.09765709 0.8747837  0.02755923]
loop took 0.03

KeyboardInterrupt: 

In [1]:
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

curses is not supported on this machine (please install/reinstall curses for an optimal experience)


In [ ]:
wwwwwwwwwwwwwwwwwwwwawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwawwwwwwwwwwwwwwwwwwwwwwwww